### ISSUE TITLE
Misleading error message (cribbed from i18next-express-middleware?)

### ISSUE THREAD

**Issue by secretworry** [sunfuze/koa-i18next#5]
Here are two error messages saying `i18next-express-middleware:: balabala`. 
* https://github.com/sunfuze/koa-i18next/blob/master/src/index.js#L72
* https://github.com/sunfuze/koa-i18next/blob/master/src/index.js#L115

That's misleading. And if you got some ideas from `i18next-express-middleware`, it's a good practice to say that you are inspired by them in your README.

**Comment by sunfuze** [comment]
u r right. fixed.
